title: Immutable Secrets and ConfigMaps
kep-number: 1412
authors:
  - "@wojtek-t"
owning-sig: sig-storage
participating-sigs:
  - sig-apps
  - sig-node
  - sig-scalability
status: implementable
reviewers:
  - "@yujuhong"
  - "@lavalamp"
  - "@msau42"
approvers:
  - "@saad-ali"
creation-date: 2019-11-17
last-updated: 2019-12-09
see-also:
replaces:

latest-milestone: "v1.19"
milestone:
  alpha: "v1.18"
  beta: "v1.19"
  stable: "v1.21"

feature-gate:
  name: ImmutableEphemeralVolumes
  components:
    - kube-apiserver
    - kubelet
disable-supported: true

metrics:
